spring:
  application:
    name: "employee-manage"
  config:
    import: "optional:configserver:http://localhost:8079/"
  data:
    redis:
      host: localhost
      port: 6379

resilience4j.retry:
  configs:
    default:
      maxAttempts: 5
      waitDuration: 100
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
