spring:
  application:
    name: "employee-manage"
  config:
    import: "optional:configserver:http://localhost:8079/"

resilience4j.retry:
  configs:
    default:
      maxAttempts: 5
      waitDuration: 100
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
