CREATE TABLE IF NOT EXISTS employee (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    reference_id VARCHAR(100) NOT NULL ,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    department VARCHAR(100) NOT NULL,
    salary DECIMAL(10,2)
);
